### ISSUE TITLE
Github teams?

### ISSUE THREAD

**Issue by chrisjenx** [cashapp/check-signature-action#7]
Is it possible to use a github team? Or repo admin? Trying to think of a way to avoid having to update this every time someone is added/removed from the repo

**Comment by yoavamit** [comment]
Good idea.
I think it'd be relatively straightforward to add that feature.
And then change the configuration to look something like:
```yaml
uses: cashapp/check-signature-action@v0.1.0
id: [unique string]
env:
  GH_TOKEN: ${{ github.token }}
with:
  allowed-release-users: yoavamit,ddz
  allowed-release-teams: cashapp:team1,some_org:team2
```
[Listing the members in a github team](https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#list-team-members) and then checking of a tag was signed by any of them or any of the individual users should be easy to do.
